spring.application.name=jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/db_biblioteca
spring.datasource.username=root
spring.datasource.password=Daniboy2@
spring.datasource.driver-class-name=org.postgresql.Driver
